### ISSUE TITLE
bug: Custom model with failed models fetch puts app in bad state

### ISSUE THREAD

**Issue by canadaduane** [menloresearch/jan#5785]
**Version:** e.g. 0.6.4

## Describe the Bug
When creating a custom model with correct API key and URL, but with a provider that does not return model names in a compatible way, the Jan app is placed in a bad state and can no longer be used. The following message is displayed:

> S.model.id.toLowerCase is not a function. (In 'S.model.id.toLowerCase()', 'S.model.id.toLowerCase' is undefined)

## Steps to Reproduce
1. Press "+" in models to create a custom model
2. Enter "https://api.together.ai/v1" as the URL
3. Enter a valid Together AI API Key
4. The app will fail to fetch the model list, entering a bad state

If you restart the app, it is still in a bad state and cannot be reconfigured.

## Screenshots / Logs

<img width="1136" height="913" alt="Image" src="https://github.com/user-attachments/assets/d4f8d401-4739-43c9-8242-ca6c35258753" />

## Operating System
- [x] MacOS
- [ ] Windows
- [ ] Linux

**Comment by LazyYuuki** [comment]
Hi @canadaduane, we will be on it immediately.

**Comment by laughedelic** [comment]
I have the same problem after misconfiguring a custom provider. I wanted to change these settings in the [data folder](https://jan.ai/docs/data-folder), but couldn't find it. Is there any other way to edit application settings outside of the UI?

**Comment by LazyYuuki** [comment]
Hi @canadaduane @laughedelic we have fixed it, it will go out with v0.6.5 tomorrow. Thanks you so much for the critical bug report!

**Comment by laughedelic** [comment]
This is what I see after upgrading to 0.6.6. It looks "nicer", but it's still the same problem and I'm not sure how to undo my bad configuration to unblock the app:

<img width="1136" height="912" alt="Image" src="https://github.com/user-attachments/assets/f9221f7e-0367-417b-a0f2-73edce247fcf" />

**Comment by LazyYuuki** [comment]
hi @laughedelic, what you could do is uninstall Jan completely first and navigate to the following folder:

`/Users/<your username>/Library/Application Support/Jan/data`

Then you can make a backup of the `threads` folder and delete everything else.

Re-install Jan and everything should be fixed.

Alternatively, if there is no information you actually want to save. You can also just delete that entire `data` folder, and reinstall Jan also.

**Comment by laughedelic** [comment]
Thanks for the detailed instructions! I got it working again 👍
